services:
  acmedns:
    build:
      context: .
      dockerfile: Dockerfile
    image: kumakaba/acme-dns:latest
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "80:80"
      - "853:853"
      - "853:853/udp"
    volumes:
      - ./config:/etc/acme-dns:ro
      - acme-dns-data:/var/lib/acme-dns

volumes:
  acme-dns-data:
    driver: local

